[tool.poetry]
name = "otus-nginx-log-analizer"
version = "0.1.0"
description = ""
authors = ["akhmadiev <akhmadiev@tax-monitor.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
structlog = "^25.5.0"
flake8 = "^7.3.0"
black = "^25.12.0"
isort = "^7.0.0"
mypy = "^1.19.1"
ruff = "^0.14.9"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^7.0.0"
pre-commit = "^4.5.1"
black = "^25.12.0"
isort = "^7.0.0"
flake8 = "^7.3.0"
mypy = "^1.19.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310', 'py312']

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
exclude = ["scripts", "docs", "test"]
disable_error_code = ["name-defined"]
explicit_package_bases = true

[tool.ruff]  # альтернатива flake8
target-version = "py312"
line-length = 120
select = ["E", "F", "B", "I"]
